- vars:
  suffix: "{{environ['EXAMPLE_SUFFIX'] | default('')}}"
  destdir: "/tmp/foo{{suffix}}"
  password: foobar

- rm:
  path: "{{destdir}}"
  recursive: true
- run:
  command: "ls -ld {{destdir}}"
- mkdir:
  path: "{{destdir}}"
- copy:
  src: foo.fernet
  dst: "{{destdir}}/bar"
  skip: if_exists
  decrypt_password: "{{password}}"
- template:
  src: foo.j2
  dst: "{{destdir}}/foo-templated"
  skip: if_exists
- cd:
  path: "{{destdir}}"
- run:
  command: "ls -ld"

#- move:
#- chown:
#- copytree:
