---
#  Most values below can use jinja2 templating syntax
- vars:
  #  pull the suffix from the environment $EXAMPLE_SUFFIX, or empty string if not set
  suffix: "{{environ['EXAMPLE_SUFFIX'] | default('')}}"
  destdir: "/tmp/foo{{suffix}}"
  password: foobar

#  Remove directory
- rm:
  path: "{{destdir}}"
  recursive: true
#  List directory
- run:
  command: "ls -ld {{destdir}}"
#  Create directory
- mkdir:
  path: "{{destdir}}"
  skip: if_exists
#  Make multiple directories via "loop"
- mkdir:
  loop:
    - path: "{{destdir}}/a"
    - path: "{{destdir}}/b"
    - path: "{{destdir}}/c"
#  Copy an encrypted file
- copy:
  src: foo.fernet
  dst: "{{destdir}}/bar"
  skip: if_exists
  decrypt_password: "{{password}}"
#  Template a file to destination
- template:
  src: foo.j2
  dst: "{{destdir}}/foo-templated"
  skip: if_exists
#  Template multiple files, default template name is destination basename with ".j2" appended
- template:
  src: "{{dst|basename}}.j2"
  loop:
    - dst: "{{destdir}}/services"
    - dst: "{{destdir}}/hosts"
    - dst: "{{destdir}}/shadow"
      decrypt_password: "{{password}}"
    - dst: "{{destdir}}/myprogram.service"
      src: systemd.j2
#  Change to directory
- cd:
  path: "{{destdir}}"
- run:
  command: "ls -ld"
