#!/usr/bin/env python3
#
#  Encrypt a file using a password.

import sys
import base64
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

if len(sys.argv) != 4:
    print(f"Usage: {sys.argv[0]} <PASSWORD> <IN-FILE> <OUT-FILE>")
    sys.exit(1)

password = sys.argv[1].encode("ascii")
kdf = PBKDF2HMAC(
    algorithm=hashes.SHA256(),
    length=32,
    salt=b'',
    iterations=960000,
)
key = base64.urlsafe_b64encode(kdf.derive(password))
f = Fernet(key)

with open(sys.argv[2], "rb") as infp:
    data = f.encrypt(infp.read())
    with open(sys.argv[3], "wb") as outfp:
        outfp.write(data)
